config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyMovies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice" style="<%= "display: none;" if notice.nil? %>"><%= notice %></p>
    <p class="alert" style="<%= "display: none;" if alert.nil? %>"><%= alert %></p>
	
	<header>
		<nav>
			<ul class="nav nav-tabs">
				<li>
					<%= link_to "Inicio", root_path %>
				</li>
				<% if usuario_signed_in? %>
					<li>
						<%= link_to "Editar perfil", edit_usuario_session_path(current_usuario) %>
					</li>
					<li>
						<%= link_to "Cerrar sesión", destroy_usuario_session_path, method: :delete %>
					</li>
				<% else %>
					<li>
						<%= link_to "Ingresar", new_usuario_session_path %>
					</li>
					<li>
						<%= link_to "Registrar", new_usuario_registration_path %>
					</li>
				<% end %>
			</ul>
		</nav>
	</header>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Bienvenido James</h1>